Herwig7: Adding GoSam and update to newer Herwig7 version
cms-sw/cmsdist pull request #2708
Opened 2016-12-06 15:44 UTC by mharrend

In this PR besides updating of Herwig7 to Herwig7.0.4 from Herwig7.0.2,
also GoSam is added as a ME provider. This ME provider is necessary since it brings with itself the golem95 library which is also required by MG5aMC@NLO.

2016-12-06 15:44 UTC, cmsbuild commented
A new Pull Request was created by  @mharrend (Marco A. Harrendorf) for branch IB/CMSSW_9_0_X/gcc530.

@cmsbuild, @smuzaffar, @iahmad-khan, @davidlange6 can you please review it and eventually sign? Thanks.
You can sign-off by replying to this message having '+1' in the first line of your reply.
You can reject by replying  to this message having '-1' in the first line of your reply.

2016-12-13 17:25 UTC, mharrend commented
Dear @smuzaffar @iahmad-khan,

could you please start the testing of this pr, too?

This an extension of #2707 which adds the GoSam event generator which is necessary since it brings the golem95 library within. This golem95 library is necessary for using any external ME provider with Herwig7-Matchbox interface.

Thanks, 

Marco

2016-12-14 13:55 UTC, smuzaffar commented
please test

2016-12-14 13:55 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2016-12-14 15:49 UTC, cmsbuild commented
-1

Tested at: 3ff813724ebd741e761c5e71021625ebf6b72272

* **Build**:

I found an error when building: 
 
 <pre>checking for the Boost unit_test_framework library... (cached) yes
checking for VBFNLO... no
checking for njet... no
checking for gosam... /build/cmsbld/jenkins-workarea/workspace/cmsdist-test-pr/testBuildDir/slc6_amd64_gcc530/external/gosam/2.0
checking for /build/cmsbld/jenkins-workarea/workspace/cmsdist-test-pr/testBuildDir/slc6_amd64_gcc530/external/gosam/2.0/bin/gosam.py... no
configure: error: GoSam requested but not found
error: Bad exit status from /build/cmsbld/jenkins-workarea/workspace/cmsdist-test-pr/testBuildDir/tmp/rpm-tmp.7Pc4c7 (%build)


RPM build errors:
Bad exit status from /build/cmsbld/jenkins-workarea/workspace/cmsdist-test-pr/testBuildDir/tmp/rpm-tmp.7Pc4c7 (%build)
</pre>

You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-2708/455/summary.html

2016-12-16 15:07 UTC, cmsbuild commented
Pull request #2708 was updated.

2016-12-16 15:09 UTC, mharrend commented
Since Herwig7 needs the gosam_env.sh script which is not build via the Gosam tarball, 
GoSam is now installed via the python installation script.

However, there is a bug due to GoSam making use of the absolute Python path. This bug only occurs after a successful build of GoSam and during the installation.
@iahmad-khan Any ideas how one could fix this?

2016-12-16 15:24 UTC, iahmad-khan commented
Do you mean python path is hard coded inside gosam ? becuse in the spec file , PYTHONPATH is set to new value before the install step.

2016-12-16 15:33 UTC, mharrend commented
Yes, it seems that inside GoSam the python path is hardcoded or at least during the rpm installation the error suggests this.

2016-12-16 15:38 UTC, iahmad-khan commented
i think you need to add the export keyword at the begging of the line that sets the PYTHONPATH

for example:

export PYTHONPATH=${CYTHON_ROOT}/${PYTHON_LIB_SITE_PACKAGES}

2016-12-16 16:33 UTC, mharrend commented
The export PYTHONPATH=... part, unfortunately, had no positive effect.
I still get the following build report:

```
Building gosam. Log can be found in /afs/cern.ch/work/m/mharrend/cmsdist/buildneu/ext/CMSSW_9_0_X_2016-11-29-2300/20161206/r/BUILD/slc6_amd64_gcc530/external/gosam/2.0/log.
source /afs/cern.ch/work/m/mharrend/cmsdist/buildneu/ext/CMSSW_9_0_X_2016-11-29-2300/20161206/r/slc6_amd64_gcc530/rpm-env.sh ; TMPDIR=/afs/cern.ch/work/m/mharrend/cmsdist/buildneu/ext/CMSSW_9_0_X_2016-11-29-2300$
Build successful.
(<function buildPackage at 0xd7b938>, <Package name=gosam>, <scheduler.Scheduler object at 0xf53c90>) done
Trying to install the rpm package external+gosam+2.0 just built.
Checking local path dependency for rpm package external+gosam+2.0 just build.
Error: Local path dependency found for external+gosam+2.0
  /afs/cern.ch/work/m/mharrend/cmsdist/buildneu/ext/CMSSW_9_0_X_2016-11-29-2300/20161206/r/slc6_amd64_gcc530/external/python/2.7.11-oenich/bin/python
Requested to quit.
Requested to quit.
Requested to quit.
Requested to quit.
* The action "install-external+gosam+2.0" was not completed successfully because Traceback (most recent call last):
File "/afs/cern.ch/work/m/mharrend/cmsdist/buildneu/ext/CMSSW_9_0_X_2016-11-29-2300/20161206/PKGTOOLS/scheduler.py", line 199, in doSerial
result = commandSpec[0](*commandSpec[1:])
File "PKGTOOLS/cmsBuild", line 2946, in installPackage
RpmBuildFailed: Failed to build package gosam.

* The action "final-job" was not completed successfully because The following dependencies could not complete:
install-external+gosam+2.0
```

2016-12-19 11:48 UTC, iahmad-khan commented
i think i needs to be build inside docker with base os image so that it can fail during the build. and then we will know what packages it tries to install from the system.

2016-12-19 11:53 UTC, davidlange6 commented
I’d suggest just grepping for the local path i the install attempt area. Most likely its in a bin area file.. 

> On Dec 19, 2016, at 12:48 PM, Ijaz ahmad khan <notifications@github.com> wrote:
> 
> i think i needs to be build inside docker with base os image so that it can fail during the build. and then we will know what packages it tries to install from the system.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2016-12-19 11:59 UTC, iahmad-khan commented
Ok , yes i guess first i should try it that way.

2016-12-19 12:31 UTC, mharrend commented
Sounds good to me. Please go ahead.
Thanks by the way

2016-12-19 14:46 UTC, iahmad-khan commented
I build it locally but i couldnt figure out so for what is the local dependency it is complaning about.

```
Error: Local path dependency found for external+gosam+2.0-cms2
  /build/cmsbuild/newbuild/slc6_amd64_gcc530/external/python/2.7.11-oenich/bin/python

``` 

but the above line is not local to the system , it is a path from build area.

2016-12-19 15:31 UTC, iahmad-khan commented
There are couple of things that @davidlt pointed out , first it should be build from source using the tarball ( by adding the tarball sources to a repo in cms-externals with some specific version ), and second , there are couple of dependencies that the install script is directly downloading such qgraf-3.1.4 , and form-4.1.033e etc that should,  instead , be added in requires list of gosam spec , from cms externals. ( by adding them to cms externals first)

2016-12-19 16:11 UTC, davidlange6 commented
The problem is the local build area dependency not the system one. Eg, 

/build/cmsbuild/newbuild…. needs to become /usr/bin/env python. There are numerous perl snippets in cmsdist to do that.

but it is basically:

perl -p -i -e "s|^#!.*python|#!/usr/bin/env python|" %{i}/bin/rootpy %{i}/bin/roosh %{i}/bin/root2hdf5

> On Dec 19, 2016, at 3:46 PM, Ijaz ahmad khan <notifications@github.com> wrote:
> 
> I build it locally but i couldnt figure out so for what is the local dependency it is complaning about.
> 
> Error: Local path dependency found for external+gosam+2.0-cms2
>  /build/cmsbuild/newbuild/slc6_amd64_gcc530/external/python/2.7.11-oenich/bin/python
> 
> 
> but the above line is not local to the system , it is a path from build area.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2016-12-19 16:43 UTC, mharrend commented
@davidlange6 @iahmad-khan 
I believe I have found a solution.

I will switch back the gosam.spec file to its original version, so that the GoSam tarball together with a make, make install is used.
Afterwards, I will provide a /bin/gosam.py manually which is needed by Herwig7 to setup the GoSam environment.
It is a little bit ugly to write the env script by oneself, but I guess it is the best option.

What do you think?

2016-12-19 20:13 UTC, davidlt commented
Yeah, the installer or something else generates some setup scripts which added full python paths into shebangs. Thus full path to Python is added to RPM requirements. I will just re-iterate what I already told to @iahmad-khan 
- Installed script downloads a tarball, but that's wrong as we cannot reproduce RPM with exact same content each time.
- Sadly configuration file has very specific version which maps to "latest" tarball, which is again not nice for reproducibility.
- There are extra dependencies being downloaded (3 or 4).

In order to make sure that we can reproduce our RPMs exactly in stable manner, we need to import the source code into cms-externals repositories, add additional dependencies as separate RPMs, etc.

2016-12-20 12:40 UTC, iahmad-khan commented
@mharrend Finally i made a successfull build with this line added to `%install section` 

     perl -p -i -e "s|^#!.*python|#!/usr/bin/env python$1|" $(grep -r -e "^#\!.*python.*" %i | cut -d: -f1)

2017-02-21 17:40 UTC, mharrend commented
Sorry, that it took me so long to come back to this issue.

I was now looking how we could include GoSam in a reproducible way. Unfortunately, I have no rights to open a new cms-externals repository.
But I would propose the following:

1) Add a GoSam repository to cms-externals
2) Add the GoSam install script from http://gosam.hepforge.org/gosam-installer/gosam_installer.py to the repository and modify the following line:
```
CONFIG_URL=r"https://gosam.hepforge.org/gosam-installer/gosam_install.cfg"
```
so that it points to a configuration file in the cms-externals repository.
3) Copy the configuration file  https://gosam.hepforge.org/gosam-installer/gosam_install.cfg to the cms-external repository and modify it.
4) Copy all external tarballs mentioned in the configuration file of 3) to the cms-external repository.
5) Make sure that the configuration file of 3) downloads the tarballs from 4) / the cms-external repository.

In this way, we could make use of the GoSam install script with slight modifications.

Looking on the many GoSam dependency I believe there is no good reason to build everything by itself.

What do you think?

If you could setup a GoSam cms-external repository, I could start to implement the steps mentioned above.

2017-02-21 17:42 UTC, cmsbuild commented
Pull request #2708 was updated.

2017-03-01 15:41 UTC, cmsbuild commented
Pull request #2708 was updated.

2017-03-01 15:54 UTC, cmsbuild commented
Pull request #2708 was updated.

2017-03-01 15:55 UTC, davidlt requested changes
First quick review, more detailed is needed.

2017-03-01 15:55 UTC, davidlt commented on form.spec
> +            --without-gmp \
Why do you disable GMP, yet in `form-toolfile.spec` use say it's being used?

2017-03-01 15:55 UTC, davidlt commented on gmp.spec
> +### RPM external gmp 6.1.2
We don't use this SPEC. GMP is distributed as part of GCC toolchain package itself. The externals should use `gmp-static` package, which does not provide shared library, just static one.

2017-03-01 15:55 UTC, davidlt commented on gosam.spec
>  %endif
You can remove this 4 line block and don't use `%cms_cxx`. It was never used.

2017-03-01 15:55 UTC, davidlt commented on gosamcontrib-toolfile.spec
> +cat << \EOF_TOOLFILE >%i/etc/scram.d/form.xml
This is wrong, looks to be copy & paste issue. This should be `gosamcontrib.xml`.

2017-03-01 15:55 UTC, davidlt commented on gosamcontrib.spec
> +%endif
Again, can be removed. We never used this once we put it.

2017-03-01 15:55 UTC, davidlt commented on gosamcontrib.spec
> +%post
You have nothing in the `%post` section thus remove it.

2017-03-01 15:55 UTC, davidlt commented on herwigpp.spec
> +
Not needed.

2017-03-01 15:55 UTC, davidlt commented on herwigpp.spec
> +	          --with-madgraph=$MADGRAPH5AMCATNLO_ROOT \
Alignment issue.

2017-03-01 15:55 UTC, davidlt commented on qgraf.spec
> +%post
Nothing in `%post` section thus remove it.

2017-03-01 15:55 UTC, mharrend commented
@davidlange6 @smuzaffar @iahmad-khan 
The PR should now be finally ready.
Can you please start the testing?

2017-03-01 15:57 UTC, mharrend commented on gmp.spec
> +### RPM external gmp 6.1.2
It was part of the CMSDIST and I got a compiler error when I was building it. So I decided to update it and the build error went away.

2017-03-01 15:59 UTC, cmsbuild commented
Pull request #2708 was updated.

2017-03-01 15:59 UTC, mharrend commented on form.spec
> +            --without-gmp \
I first tried it with gmp but always the libgmp.so.3 was not, thus, I removed it in the form.spec and forgot to do it in the form-toolfile.spec, too.

2017-03-01 16:00 UTC, cmsbuild commented
Pull request #2708 was updated.

2017-03-01 16:02 UTC, cmsbuild commented
Pull request #2708 was updated.

2017-03-01 16:03 UTC, cmsbuild commented
Pull request #2708 was updated.

2017-03-01 16:04 UTC, cmsbuild commented
Pull request #2708 was updated.

2017-03-01 16:04 UTC, mharrend commented
@davidlt Can you review it again, please?

Thanks

2017-03-06 09:22 UTC, mharrend commented
@davidlt @davidlange6 I have commented all the reviewed points and also changed it according to your proposal. So, can you please start the tests or comment further?

Thanks, Marco

2017-03-06 09:24 UTC, smuzaffar commented
@iahmad-khan , can you please try building it locally?

2017-03-06 09:57 UTC, smuzaffar commented on gosam.spec
> +CXX="$(which %{cms_cxx}) -fPIC"
cms_cxx is not defined. I would suggest to replace it directly with g++. same for gosamcontrib.spec

2017-03-07 09:36 UTC, cmsbuild commented
Pull request #2708 was updated.

2017-03-07 09:37 UTC, cmsbuild commented
Pull request #2708 was updated.

2017-03-07 09:38 UTC, smuzaffar commented
@mharrend, @iahmad-khan is working on it and will make a PR for 91X

2017-03-07 09:38 UTC, cmsbuild commented
Pull request #2708 was updated.

2017-03-07 09:39 UTC, mharrend commented
@smuzaffar @iahmad-khan Thanks for working on it! I just updated the cms_cxx part. But will now refrain from updating parts.

2017-03-13 14:03 UTC, smuzaffar commented
closing it in favor of #2889 for 91X

2017-03-13 14:03 UTC, closed without merging

2017-04-10 13:10 UTC, Andrej-CMS commented
Hello @mharrend, @smuzaffar , @iahmad-khan ,

Would you please explain why this PR was closed in favor of 91X? These changes are necessary for Herwig7 in order to work in CMSSW_9_0_X. 

Cheers,
Andrej

2017-04-10 13:19 UTC, smuzaffar commented
@Andrej-CMS , new externals should first go in dev release (which is 91X now). There are also some fixes in  #2889 too (which are missing here). Once that PR is in 91X (and if needed for 90X) then we will create a backport PR for 90X.

2017-04-10 13:25 UTC, Andrej-CMS commented
@smuzaffar thank you very much for the fast reply! I've seen that #2889 ist on hold for quite some time. Will there be a follow up on the PR in the near future? 

As I already said, this is required for the new Herwig7 interface for CMSSW

2017-04-10 13:45 UTC, smuzaffar commented
I guess there might be license related issue as gosam and form are GNU GPL v3. I am not a guru on license so I let @davidlt and/or @davidlange6 to comment